# Linux Build Configuration for Travis

sudo: false

language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.7

install:
  - pip install --user cpp-coveralls

  - if [ "$CC" = "gcc"   ]; then export CC=gcc-4.9 CXX=g++-4.9; fi       # Make sure that gcc-4.9 is selected.
  - if [ "$CC" = "clang" ]; then export CC=clang-3.7 CXX=clang++-3.7; fi # Make sure that clang-3.7 is selected

script:
  - cd test && make clean && make && make test
  - find .. -name '*.cc' -not -path '../test/*' | xargs gcov-5 -n -o ..

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls -b test -r .. -e test -x cc --gcov-options '\-lp'

notifications:
  email:
    recipients:
      - lonnywang@qq.com
    on_success: change
    on_failure: always
