# Linux Build Configuration for Travis

sudo: false

language: cpp

os:
  - linux

compiler:
  - gcc

cache:
  apt: true

addons: &gcc5
  apt:
    packages:
      - gcc-5
      - g++-5
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9

install:
  - pip install --user cpp-coveralls

script:
  - export CXX=g++-5
  - cd test && make clean && make && make test

after_success:
  - cd ..
  - coveralls -b test -e test -x cc --gcov-options '\-lp'
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - lonnywang@qq.com
    on_success: change
    on_failure: always
